### ISSUE TITLE
User can register without accepting privacy policy

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/land-explorer-front-end#103]
Should probably only allow the user to click register if the privacy policy checkbox has been ticked

**Comment by lin-d-hop** [comment]
This is in review with no testing notes or PR. 
Can we add the relevant commits to a PR please?

**Comment by lin-d-hop** [comment]
Just checked on staging and 'Register' is greyed out until you click 'agree to privacy policy'. This is the intended behaviour.

In future let's use the PR process and include some notes on what to test please @rogup :pray: Thanks :)
