### ISSUE TITLE
Document deployment process on wiki

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#106]

**Comment by rogup** [comment]
Is there a doc with some of this information on the google drive? I remember seeing it once but can't find it.

**Comment by King-Mob** [comment]
@rogup up on the wiki here: https://github.com/DigitalCommons/land-explorer-front-end/wiki/Deployment-Processes

**Comment by rogup** [comment]
@King-Mob Thanks

**Comment by King-Mob** [comment]
@lin-d-hop still new at writing open source documentation, happy to close if you think rohit and I have self-assured the quality

**Comment by lin-d-hop** [comment]
:) Loving the documentation
I guess the main thing is that as a team we keep it updated if things change and use it to onboard new people. Then when noobs find issues they can update it too.

LGTM
