### ISSUE TITLE
Automatically add users to LX marketing emails

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#116]
## Description
When a user registers for an LX account they are given the option to sign up to LX marketing emails.
It would be great if we can add new users to our marketing list automatically.

## Acceptance Criteria
- New users that have ticked the marketing box are subscribed to the Digital Commons mailing list with the tag `LandExplorer Marketing`
- Users that have not ticked this box are not subscribed
- You only need to consider new users. We can manually ensure old users are synced from the date of deployment.

## Useful Links
Find the relevant API [here](https://api.buttondown.email/v1/schema#tag/Subscribers/operation/Create%20a%20new%20subscriber).
Our maililng list is managed through [ButtonDown](https://buttondown.email/). Find the login details in Bitwarden.

**Comment by King-Mob** [comment]
I did this issue on the back-end, I'm not sure how to link PRs across repos. It's up on staging though so it is possible to test if you get the newsletter verification email when you sign up

**Comment by lin-d-hop** [comment]
@King-Mob  one option would be to transfer the issue to the backend then link the PR. You can do that using the 'Move Issue' button on the bottom left menu.

**Comment by lin-d-hop** [comment]
LGTM

Love this addition!!
