### ISSUE TITLE
Imported Markers are not included in shared maps

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#117]
~~**Describe the bug**~~
~~When you share a map only drawn markers are shared. Any markers from the 'layer' experience - imported markers - are left off the shared map.~~

~~**To Reproduce**~~
~~Steps to reproduce the behavior:~~
~~1. Turn on layers that include markers eg RGS data~~
~~2. Click on Share Map and share with another user~~
~~3. Open the map in the other user account~~
~~4. See that there are no markers~~

~~**Expected behaviour**~~
~~All kinds of markers should be shared in a shared map - drawn and imported.~~

~~**Context (please complete the following information):**~~
~~ - Device: [e.g. iPhone6] - Desktop~~
~~ - OS: [e.g. iOS8.1] - Ubuntu~~
 ~~- Browser [e.g. stock browser, safari] Chrome~~
~~ - Version [e.g. 22] October Release~~

~~**Additional context**~~
~~Add any other context about the problem here.~~

The above is the expected behaviour of LX. So this issue has been updated to add a feature that enables maps and map data/elements to be shared to anyone.

## Description
Until we build out more features around collaborating on maps and assigning permissions and roles to different kinds of map users, we need to have a way for people using data from data groups to make their maps shareable to folks outside of their groups.

We propose adding a 'Save map' function -> Publish Snapshot. This means there will be two functions in 'Save Map':
1. Save Map
Explaining text: Save the current map to edit later. All markers, lines, polys and layers will be saved and can be edited later. Choose this option if you wish to continue editing your map later.

2. Publish Snapshot
Explaining text: Publish a snapshot of this map. This map will save as read-only, meaning you won't  be able to edit it later. Choose this option if you wish to share your map publicly.

The user will need a way to select between these two types of saving ping @MelissaMc20.

## Acceptance Criteria
- A Snapshot should be able to be shared, exported as geojson and downloaded as a shapefile. Sharing is critical. Note if either of exporting as geojson or downloading as a shapefile take longer than 30mins to implement then let's park them for later issues. Let me know in the PR desc.
- Save map will continue to function as it does now.
- Publish Snapshot will allow a user to name a map that cannot be edited later. Note - In reality we need to make the minimum possible changes so:
      - if layers can still be edited that's fine, if not that's great too. 
      - Popup boxes should not be edtiable
      - Users should not be able to add these markers to their existing map.

**Comment by King-Mob** [comment]
@lin-d-hop the other user, they are in the same user group?

**Comment by rogup** [comment]
I tested this for sharing a map with a public layer (agricultural land classification) visible without markers, and it worked fine.

@King-Mob which layer is RGS, and do I need to be granted access to this in order to see it on production?

**Comment by lin-d-hop** [comment]
@rogup The RGS layers are markers. 
You can add yourself to the RGS group by adding your user id to the user_group_memberships table. Do this directly in the database, the RGS user group is user_group_id=1;

You can then view the markers by turning on the Resilient Green Spaces layers in the layers menu.

These are the layers that we want to be able to share in shared maps.

Let me know if you get stuck figuring this out. It should be quite straight forward but obviously 'inserting' into a production database is something that should not be done lightly :)

**Comment by King-Mob** [comment]
@lin-d-hop I can only reproduce this if the second user isn't in the user group that has access to that layer.

Ah, I realise that I accidentally added a step in reproducing.

Turn on layers that include markers eg RGS data
**Save the map [added this step]**
Click on Share Map and share with another user
Open the map in the other user account
See that there are no markers

**Comment by lin-d-hop** [comment]
Okay, so is this the expected behaviour?
When you share a map you aren't actually sharing the markers or layers, you are sharing the settings that give access. It makes it impossible to use imported data for the purposes of telling a story to people (which is a key need of users). The feature that I would like is to be able to share the whole constructed map as a snapshot.

Do you have an idea of the complexity of enabling the markers of a map to be shared from a data group that a user doesn't have access to?
I guess this needs more thinking about consequences before moving ahead.

**Comment by King-Mob** [comment]
Yes, this is the expected behaviour.

You can share the markers by saving them to your map first, then sharing the map. So the complexity of enabling the markers of a map to be shared from a data group the receiving user doesn't have access to could be modeled as a mass `save to map then shared map`. This seems to me kind of like a `save layer to map` feature. Not too difficult, because the back-end already can save one, so just looping over that is easy.

Communicating what is happening to the user seems the bigger challenge, or why what they're trying to do isn't working

**Comment by rogup** [comment]
@lin-d-hop Thanks, I'll have a go at that.

@King-Mob Saving all markers from a layer to a map feels like it would put a lot of load on the DB, if people regularly do that to share maps. And then if the layer's data changes, we would end up with duplicates of data on people's maps that are slightly out of sync.

I wonder if it would be better to have a mechanism for users with read-access to a data group to have the option of sharing that acess when inviting others to their map? e.g. some sort of access control like Google Docs, where the owner of the datagroup has the master controls to revoke access.

**Comment by King-Mob** [comment]
I agree it would be preferable to stay within the user group model, but I think the feature being asked for is about sharing beyond the user group? 

Maybe another share option, "share as snapshot", with a bit of info about what that entails is the way to go?

**Comment by rogup** [comment]
Hmm ok I get what you mean about wanting to share outside the user group.

If we're wanting to share all the data in a datagroup with an external user, granting the user access to the data group without duplicating all the data feels doable, without necessarily adding the user to the same user group
e.g. could we have a 'guest access' user group that exists for each data group, that users can be added to behind the scenes when sharing a map with layer data?

I don't know if this would end up being harder in practice but probably worth exploring.

**Comment by King-Mob** [comment]
Add new save method:

 publish snapshot -> readonly for everyone, appears in mymaps or sharedmaps
	- converts everything on the map to drawn objects
	- can be shared via geojson and other methods

**Comment by King-Mob** [comment]
@lin-d-hop idle musing: put the date of the snapshot somewhere visible in the UI? it's already in the database, helps reinforce the idea that it's not live data?

**Comment by lin-d-hop** [comment]
Nice Idea. Perhaps, for now, with the name of the map in the bottom corner (this will move soon)
Like:
**MyMap1**
Snapshot taken [date]

**Comment by MelissaMc20** [comment]
Are you only able to save/share a snapshot of a map if it's saved? Or can you do it on a map you haven't saved yet and potentially wont save?

**Comment by lin-d-hop** [comment]
Publishing a Snapshot is a saving process. A Snapshot is a type of save.

**Comment by MelissaMc20** [comment]
So proposed flow of > 

Save > Modal pop out of 'Save Map for later OR Save Map as snapshot' 

Save Map for later > (current flow) Name map > Map saves > Map stays open & appears in 'My Maps' 

Save Map as Snapshot > Name Snapshot > Snapshot saves > Would you also like to share? > Yes (takes you down current share flow pop outs, except it's for the snapshot instead, has explainer text to tell them what they're doing) > OR No > Modal Popout saves 'you can view your snapshot in 'My snapshots' as Read Only & can also share from here at a later time' 

New section in top drop down 'My Snapshots' > Open or Share > Open, opens map as Read Only (text somewhere to save it's read only) > OR share, share open's up current shareflow pop outs but for the snapshot instead. 

??? Share icon - new modal pop out before the current 1st one, saying share snapshot or map. 

Clarifying questions: - would you like to be able to share from the main share icon like this for snapshots? Yes/No? 
Would you like to be able to share from the 'My Snapshots' drop down? Yes/No

**Comment by lin-d-hop** [comment]
This is meant to be a quick addition, rather than a whole new UX flow. From a user perspective I'd like to keep snapshots unconfusing and as similar to maps as possible. 

Would it be possible for the flow to be:

Save > Modal pop out of 'Save Map for later OR Save Map as snapshot'

Save Map for later > (current flow) Name map > Map saves > Map stays open & appears in 'My Maps'

Save Map as Snapshot > (current flow) Name Snapshot > Map saves > Map stays open & appears in 'My Maps'

Perhaps we also add a way of distinguishing Snapshots from Maps in the My Maps section. Eg Name, Type, Modified. Type might be an icon (eg camera or map icon) with hover text Snapshot, Map.

All this functionality will be moving to the top menu when we build that and I'd like to keep UX changes minimal until be make the big shift.

What do you think @MelissaMc20?

**Comment by MelissaMc20** [comment]
Makes sense to me :)

**Comment by MelissaMc20** [comment]
https://xd.adobe.com/view/b6ec66fd-fee7-463b-a7c9-70a9b50f3023-e3bf/

Voilá - two flows, click on the MM icon on the top right > my maps > to see the new look including 'Type' (please include hover text on these icons for 'map' and 'snapshot') - press the close button to go back. 
second flow > press save > be greeted with a new modal > both options will take you to the existing save modal (although one will be for saving as a map, and one for snapshot) - (please inlclude hover text for these to describe what they do'

**Comment by lin-d-hop** [comment]
@MelissaMc20 I realise now that you were totally right on the saving process you described above :facepalm: We should have gone with something closer to your original ideas, rather than the version I described. D'oh!!! Sorry for not taking more time to absorb the full implications of your suggestions. Can I hit you up for some changes next week?
