### ISSUE TITLE
Grant write access for map to another user

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#122]
**Description**

Users need to be able to share maps with each other that they can edit and then send back.

**Acceptance Criteria**

Can open a share map, edit the map (e.g. add a marker), save it, and then have the owner of the map see the new version.

**Comment by King-Mob** [comment]
@lin-d-hop so i'm basically creating a new map access type, previously we had owner who can write and viewer who can read. i'm adding editor, who can write but can't delete.

Can editor add other editors and viewers?

**Comment by lin-d-hop** [comment]
Hi @King-Mob This feels like a big decision I'd like to understand before we implement. 
Would be great to have a chat about it.

**Comment by King-Mob** [comment]
@lin-d-hop yes, for sure. Was planning to start at 12:30 tomorrow if you're free to talk about it then

**Comment by lin-d-hop** [comment]
Shall we park this issue for now and put some real design effort into the 'Collaborative Mapping' epic?
@King-Mob

**Comment by lin-d-hop** [comment]
Closing and moving to Collaborative mapping epic.
