### ISSUE TITLE
Save and edit Name/Description boxes

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#126]
## Description
We're adding additional functionality to our Name/Description boxes. We need some designs for this.

Flows that enable:
1) Adding the map element to a saved map
2) editing the Name and Description

**1. Adding the map element to a saved map**
a) A button with hover text for adding/saving element eg 'Add to my map'
b) Then the user is given the option of which of their saved maps they wish to add this element to
(later it would be good to be able to create a new map from here, but this is not a current priority)

Currently it looks like this:
![Screenshot from 2022-10-26 18-08-18](https://user-images.githubusercontent.com/8669848/198097568-5f1477e3-611c-4fed-8c15-723ea7f86117.png)
![Screenshot from 2022-10-26 18-08-29](https://user-images.githubusercontent.com/8669848/198097588-a0a8bf09-d0ec-4edf-aa12-e19d637243b8.png)

_From call 27/10
Plus symbol for adding to the map.
Notes below on some missing aspects from the original designs
Scroll on choosing which map to save to is a bit clumsy
Option for 'save' icon or tick/cross -> save, cancel icons
Let's try have consistency between icons vs words eg all icons_

**2. Editing the Name and Description**
a) A button with hover text for editing the text fields
b) Then a button to save the edits and cancel the edits

_From call 27/10
Edit symbol for editing the name/desc
Text box appears around the text as per the existing drawn markers.
Option for 'save' icon or tick/cross -> save, cancel icons
Let's try have consistency between icons vs words eg all icons_

## Acceptance Criteria
- The map elements and text are of an appropriate size to ensure accessibility to users (they are currently very small)
- Clear hover text. How long should a hover last before the text appears? (let's create a standard through the app)
- Clear, simple icons that are easy to distinguish from each other (is the save icon appropriate for 'adding element to saved map'?)

**Comment by lin-d-hop** [comment]
@MelissaMc20 Hopefully this is clear, but let me know if you want to chat anything through.

**Comment by MelissaMc20** [comment]
@lin-d-hop Possible to have a chat about this?

**Comment by lin-d-hop** [comment]
Points from call..

The following has not been implemented in the existing design
- Change Name to H2
- Font size - currently px and change to rel
- Box gets smaller as you zoom in and thus becomes too small. Should stay the same size.
- Onhover = grey hover map name when saving to a map

**Comment by MelissaMc20** [comment]
https://xd.adobe.com/view/a9b0649c-132d-482c-a89c-50582e032342-fce3/

Think I've got everything but if not let me know if something's missed. 

I've left it on the speak bubble icon, this allows you to use it as a prototype too. (you can also click through all the screens at the bottom, but you need to use the prototype to be able to see the hover functions)- once you've viewed the prototype properly and understand behaviours swap it to the </> symbol to be able to export the icons used. 

How it functions:
Screen 1, click the pin.
Screen 2, hover over the plus & pencil icons to see the hover behaviour. Info text should appear. Click on either of the icons (you can do this again for the other icon when you get back to the closed pin.) 
Screen 3 (if you choose the pencil), you can either close the box which takes you back to the state where the marker pin has no pop out, press on the red x which takes you back to the opened pop out, or the tick which will save any changes you made when clicking on the grey fields and edditing the text. (you can then try the other flow)
Screen 3 (if you click the plus icon), you can hover over map one to see the hover effects, all clickable icons (cross and tick) should have info text on hover also (not included on this screen as it's the same as the previous one with different text) on press, on Map 1 it swaps from the hover effect to a green highlighted background with white text. You can then, press the red cross to cancel, the cross to close the pop out or the green tick to save your selection. 
Screen 4, should notify you which board you saved the pin to. 

I'm not sure of the text size on h2 but feel free to just change it to whatever you have it inside the style sheet already, I tested it on f12 and the h2 size seemed fine to me. 

The behaviour of the box on scroll currently reacts how the pins do (it goes smaller the more you zoom out) it should function more like sea-map's pop out, staying the same size as you zoom until you get to a certain point it will close itself.

**Comment by lin-d-hop** [comment]
@MelissaMc20 this is a sexy design! Thank you!

**Comment by lin-d-hop** [comment]
Designs complete. I believe this work is being completed in #123

**Comment by lin-d-hop** [comment]
All looking good to me. THanks!
