### ISSUE TITLE
Can add markers to snapshot maps, which then opens the map in live mode

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#128]
1. From a clean refresh, turn on a data group layer
2. Click on one of the data group items, and add to map
3. In the list of maps, select a map you know is a snapshot
4. add to that map, press ok
5. the snapshot is now open as a dynamic map and markers can be added to it etc

**Comment by lin-d-hop** [comment]
THis is working well :)
There is a clunky UX when you create then save a map as a snapshot. THere is no way to know in advance that once you save as a snapshot you are totally stuck. You can't edit, you just have to make a new map. I'll open another issue to make sure we communicate this to the user more effectively.
