### ISSUE TITLE
Remove the ecommerce experience in LandReg data

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#135]
## Description
Our ecommerce experience doesn't work, was never intended to work. It shouldn't be in production.
![Screenshot from 2022-11-03 10-21-49](https://user-images.githubusercontent.com/8669848/199701476-24d2c8e8-989d-441e-9c21-1e5ff0d1ef13.png)

Let's remove it.

Can we include Title and Plan IDs where we currently display the prices.
Can we also include a link to where people can access this on LandReg

Eg:

Title ID - xxxxxxxx
Plan ID - xxxxxxxxx

_You can access these documents for a small fee by visiting the LandRegistry website using the above IDs: 
https://search-property-information.service.gov.uk/search/search-by-inspire-id_

## Acceptance Criteria
1. Hide ecommerce experience (we may want it later)
![Screenshot from 2022-11-03 10-45-53](https://user-images.githubusercontent.com/8669848/199701641-379307d4-7bf6-4575-917c-0a3c13b79b50.png)

2. Remove ID numbers where they have no description
![Screenshot from 2022-11-03 10-46-08](https://user-images.githubusercontent.com/8669848/199701746-c3ca8196-ab51-4874-9d7c-fef32d37a875.png)

3. Change the 'add to cart' buttons into description boxes giving the Title and Plan INSPIRE IDs:
```
Title register ID - xxxxxxxx
Title plan ID - xxxxxxxxx
```
![Screenshot from 2022-11-03 10-47-40](https://user-images.githubusercontent.com/8669848/199701969-544113ec-8236-4b07-85a0-a63ee5d3deaf.png)

4. Add tooltip to Title and Plan in the boxes above giving information on what the difference between them is:
`The Title Register gives information on who owns the property or land, and any rights of way`
`The Title Plan includes the property or land’s location and boundaries`

5. Add text saying how people can access the titles/plans:
```
_You can access these documents for a small fee by visiting the LandRegistry website using the above IDs: 
https://search-property-information.service.gov.uk/search/search-by-inspire-id_
```

**Comment by King-Mob** [comment]
@lin-d-hop some of the acceptance criteria might not be possible, I'm not sure if we have title and plan IDs. I'll look into it though

@lin-d-hop would you like to do anything with the "property information search" where people enter a postcode? it's currently not connected to anything, it just gives the impression you can get property information for particular addresses

**Comment by King-Mob** [comment]
@lin-d-hop I've put a version of this on staging. I'm not sure that the register or plan IDs are correctly labelled, but you can verify whether it looks how you expected

**Comment by lin-d-hop** [comment]
> do you have an example of a "description box"

In the original issue I put the image of the current buttons in this section as a suggestion of what the description box could look like. I think it would be good to separate from the original text in some way.

@MelissaMc20 I wonder if you can make a very quick proposal?
![Screenshot from 2022-11-21 15-30-06](https://user-images.githubusercontent.com/8669848/203094011-754cee57-3b27-493f-aa73-b6a7fea1e07f.png)

:point_up: I think it would be good if the Title ID and Plan ID stood out a little more instead of blending into the rest of the text. Any ideas of a nice simple way to do this?

**Comment by King-Mob** [comment]
@lin-d-hop the first code is the polygon ID, I think this can also be called the INSPIRE id, although I would need to check if those are two different numbers.
the second one is called the title number in the code, I think it might be the same as the title registration but I can also check that.

**Comment by lin-d-hop** [comment]
Other notes:

After playing with usage, let's call the 'Title register ID' -> 'INSPIRE ID' (checked on Land Reg)
Let's go with 'Title Number' for the other once we can confirm that.

Link to Land Reg should open in new window.

**Comment by King-Mob** [comment]
Cool, that's on staging. I'll make a PR when @MelissaMc20 gives us a box opinion

**Comment by MelissaMc20** [comment]
![image](https://user-images.githubusercontent.com/59023121/203979967-f37815f5-b6c3-4e01-b02f-a2a9d733ab3c.png)
Thoughts?

**Comment by King-Mob** [comment]
1. Looks nice
2. Interesting that all our example screenshots are from the Midlands. I do this as well, just scroll in on the middle of the map

**Comment by lin-d-hop** [comment]
great :) thanks @MelissaMc20

**Comment by King-Mob** [comment]
@lin-d-hop @MelissaMc20 up on staging. I have adapted the design because the property card is in a different place but I think the idea is the same.

**Comment by lin-d-hop** [comment]
@King-Mob noticed that you've not been linking PRs. I'm missing your testing notes.

**Comment by King-Mob** [comment]
@lin-d-hop sorry about that, I ended up completing this in #136 , I've put testing notes over there

**Comment by lin-d-hop** [comment]
Looking good!
We get a few emails from people wondering why they can't buy the records, so very pleased this is getting through the pipe. Thank you!
