### ISSUE TITLE
New markers are named Marker NaN

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/land-explorer-front-end#140]
This is a regression due to https://github.com/DigitalCommons/land-explorer-front-end/commit/30dc461f36f384be14abcfe39fcfca291b32bcee

In the markers redux data, we changed the badly named field 'id' to 'markersDrawn', which is used to work out the name of the next marker by incrementing the count. In old maps where the data still has 'id' instead of 'markersDrawn', the calculation therefore fails and we get an undefined number.

- Full fix: Adding a bit of migration code when loading an old map, which changes the 'id' field in the data to 'markersDrawn'.
- Quick fix: If we don't care about the count being reset for existing maps on production, we can have a simpler bit of code to just start naming new markers from 1 again if 'markersDrawn' doesn't exist yet.

This same fix will also need to be done for the Drawings redux data, since polygonCount and lineCount have been named to polygonsDrawn and linesDrawn.

**Comment by rogup** [comment]
@lin-d-hop Do you think we should go for the full fix?

**Comment by rogup** [comment]
@lin-d-hop It just means that new markers will be named Marker 1, Marker 2, etc. even if there are existing markers, so the names might clash

**Comment by King-Mob** [comment]
@lin-d-hop @rogup Having some numbering as a default naming system sounds like an ok system, but i wouldn't worry about names clashing given that the name is just a name. Getting rid of NaN is good, personally don't care whether it's by fixing the numbering or just changing the new marker name to "New Marker"

**Comment by rogup** [comment]
Cool I'll go with the quick fix which isn't much work
