### ISSUE TITLE
Popup doesn't appear for drawn marker that is in a group

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/land-explorer-front-end#144]
When a drawn marker is in a group with nearby markers, the popup doesn't appear (to visually indicate that it's the active marker, or in order to edit the name). The only way to make it appear is to zoom in enough that the group separates.

Ideally the popup would show if you click the marker's info in the Info menu section. And maybe something should happen when clicking a group, since they seem clickable?

**Comment by rogup** [comment]
@King-Mob this is related to your recent UX enhancement to group drawn markers

**Comment by King-Mob** [comment]
@rogup also doesn't appear for data group items when they're clustered either. Agree with your intuition that something should happen when clicking on them. On MykoMap, which I borrowed the cluster icon from, clicking on the cluster zooms to the level at which the first marker breaks out from the cluster.

**Comment by lin-d-hop** [comment]
I'm going to close this issue and reopen. From the issue it's not clear what actions should be taken so hard to know if it has been done.
