### ISSUE TITLE
Drawing tools are not deselected when changing tool

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/land-explorer-front-end#148]
Click Drawing Tools > Polygon
Don't draw anything, then click Marker
It looks like only the Marker is selected, but when you start creating markers, a polygon gets drawn at the same time.

The same happens for Lines.

**Comment by lin-d-hop** [comment]
As discussed in meeting 17/11 - when drawing the tool bar collapses after you finish drawing. This is strange UX. It would be great if it stayed open.
