### ISSUE TITLE
Functionalise all remaining class-based components

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#156]
Edit this to add stuff to the list. 

List:

- [ ] components\BackgroundImage.js
- [ ] components\Controls.js
- [ ] components\CouncilMenuKey.js
- [ ] components\Draggable.js
- [x] components\Drawing.js
- [ ] components\DrawingLayers.js
- [ ] components\ForSaleMarkers.js
- [ ] components\Geocoder.js
- [ ] components\Key.js
- [ ] components\MapboxMap.js
- [ ] components\MapCommunityAssets.js
- [ ] components\MapCouncilLayers.js
- [ ] components\MapForSaleMarkers.js
- [ ] components\MapLayers.js
- [ ] components\MarkerPin.js
- [x] components\Markers.js
- [ ] components\MarkerSection.js
- [ ] components\MenuKey.js
- [ ] components\MenuLayers.js
- [ ] components\MenuMain.js
- [ ] components\MenuProfile.js
- [x] components\Modals.js
- [x] components\Nav.js
- [x] components\Navbar.js
- [ ] components\NavCommunityAssets.js
- [ ] components\NavDrawingTray.js
- [ ] components\NavForSale.js
- [ ] components\NavLandOwnership.js
- [ ] components\NavPoliticalData.js
- [x] components\NavTray.js
- [ ] components\PolygonSection.js
- [ ] components\ProfilePic.js
- [ ] components\PropertyList.js
- [ ] components\PropertyListing.js
- [ ] components\Tooltips.js
- [ ] components\ZoomWarning.js
- [ ] components\common\CouncilNavTrayItem.js
- [ ] components\common\Loading.js
- [ ] components\common\Modal.js
- [ ] components\common\MultipleNodal.js
- [ ] components\common\NavTrayItem.js
- [ ] components\common\NavTraySection.js
- [ ] components\common\Nodal.js
- [ ] components\common\ToggleSwitch.js
- [x] components\modals\MyMaps.js
- [ ] components\modals\MySharedMaps.js
- [ ] components\modals\Save.js
- [x] components\modals\EmailShare.js
- [ ] routes\Authentication.js
- [ ] routes\ChangeDetails.js
- [ ] routes\ChangeEmail.js
- [ ] routes\ChangePassword.js
- [ ] routes\FourOhFour.js
- [ ] routes\Login.js
- [x] routes\MapApp.js
- [ ] routes\MyAccount.js
- [ ] routes\Register.js
- [ ] routes\ResetPassword.js

**Comment by rogup** [comment]
Let's wait for #124 before resuming this, otherwise we'll get loads of merge conflicts

**Comment by lin-d-hop** [comment]
So far so good. Just awaiting info on the issue mentioned in #225 to see if it is related
