### ISSUE TITLE
[Spike] Create a game plan for adding unit tests across LX

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#164]
## Description
We want to add unit tests across LX. 

It would be good to develop a plan from here (no unit tests) to there (100% coverage). We'll need to think about frameworks, any training that would be helpful. 

It would also be helpful to identify which classes would benefit most from testing. Are there some that feel particularly buggy? Are there some that are just blackboxes and it would be good to understand them better? Or should we start the most recently written classes that are still fresh?

It would be great to timebox this. We don't need an exhaustive list to get started, we just need a strategy of where to start. Is two hours long enough to get us ready?

## Acceptance Criteria
- Identify appropriate test frameworks for frontend and backend
- Identify any training needs for the team
- Identify a plan of execution - which classes should we start with?

**Comment by lin-d-hop** [comment]
Agreed that 2hrs should be a good amount of time. Timebox to half a day.

**Comment by King-Mob** [comment]
@lin-d-hop discussion happened, we have a plan, document linked on element with the answers to the questions at the bottom

**Comment by lin-d-hop** [comment]
LInk to outputs:
https://docs.google.com/document/d/1zIwBDMYQFnWV6af6W3z_yEkuhc5AyCbtvXrGIB8Bgg4/edit
