### ISSUE TITLE
Add Administrative Boundaries Layer

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#170]
## Description
Administrative Boundaries as a layer in LX can aid organisers to coordiante efforts around local and regional governance. A requested feature and strongly in line with our raison d'etre.

To do this let's try the [BoundaryLine](https://www.data.gov.uk/dataset/d310b2c5-5253-4bc2-a78d-f8240293119d/boundary-line) data set. This dataset has the following layers:

- European region
- Counties
- District Borough Unitary
- Greater London constituencies
- Westminster constituencies
- Scotland and Wales constituencies
- County electoral divisions
- Scotland and Wales regions
- Unitary electoral divisions
- parish
- District borough unitary ward

We wish to add a new layer section: Administrative Boundaries
Within this section we wish to include the following layers:
- Wards (using District borough unitary ward)
- Parishes (use parish)
- Local Councils (using District Borough Unitary)
- Parliamentary Constituencies (using Westminster constituencies)
- Devolved Powers (combining Greater London constituencies, Scotland and Wales regions)
- Counties - (using Counties)

## Acceptance Criteria
- New section within the Layers tab called Administrative Boundaries
- Section expands and contracts in the same way existing sections do
- New section contains the 6 layers specified above
- Layers can be toggled with multiple displayable concurrently as current layers do

## Outstanding questions

Does the district / borough/ unitary contain the same (but more) data as "unitary electoral divisions" or is there an important distinction there?

Will the dataset be downloaded and static? Or loaded dynamically? If the former we need to agree an update schedule and implement an automation. I would suggest twice a year.

**Comment by kateswade** [comment]
This looks good to me! @lin-d-hop 
two mini refinements:
- I'm not sure if "counties" aligns exactly with unitary authorities - but if it does then we might not need "counties" as well.
- Feels like these things don't change frequently but when they do it is significant - so it might be worth having a regular update twice yearly as you suggest but also listening out for news (maybe a google alert?) about boundary changes and doing ad hoc updates as necessary?

One thing I can't quite envisage in my head is how easy this will be for people to navigate - for some (many!) locations they will be in a parish, a ward, a district, a unitary, a constituency and a county, so working out how all the lines work well together in an intelligible way might need some design and creative time :)

**Comment by lin-d-hop** [comment]
Okay, I think we might want to look at the data on this to get a more clear picture. 

As an example - The County of Gloucestershire has 7 council areas, 1 unitary and 6 county councils.
My hope is that 'County' layer outlines Gloucestershire and 'Local Council' layer outlines the 7 areas.
![Screenshot from 2023-01-17 00-48-22](https://user-images.githubusercontent.com/8669848/212786635-2fabb197-27ce-417b-8132-fa5bd58121c8.png)

Why can't they break things up neatly :facepalm:

**Comment by King-Mob** [comment]
@lin-d-hop @kateswade is it possible that this data has gaps in? some counties and wards appear to be missing when I open it in mapbox studio

**Comment by rogup** [comment]
https://gis.stackexchange.com/questions/174727/ordnance-survey-missing-counties-from-boundary-line-shapefile

**Comment by King-Mob** [comment]
@lin-d-hop some answers to the (as ever) outstanding questions:

> Does the district / borough/ unitary contain the same (but more) data as "unitary electoral divisions" or is there an important distinction there?

They are different, here's a picture that shows the difference. The unitary electoral divisions contain more detailed divisions for some sections of the data
![qgis unitary electoral divions vs district borough unitary](https://user-images.githubusercontent.com/38507954/225003150-ed834786-bcbc-4f7e-8abe-6edd339c2379.png)

> Will the dataset be downloaded and static? Or loaded dynamically? If the former we need to agree an update schedule and implement an automation. I would suggest twice a year.

The dataset is downloaded and static. Twice a year makes sense in terms of cadence. An automated update is challenging because I used Mapbox Studio to get the tilesets up there; the mapbox tilesets api (MTS api) has a different billing structure. We would need to look at the endpoints for updating tilesets as well which is different from creating them.

None of these things are impossible just flagging as taking some time.
