### ISSUE TITLE
Implement Menu System

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#174]
## Description
Implement the drop down menu in the new menu system.

Design are here:

#### Changes from Design
Menu system should include:
- New
- Open (this does not have a submenu for Snapshot/Editable and instead opens the box with both displayed)
- ~Save~
- ~Save as~ Save a copy
- Create Snapshot
- Share
- Export Shapefile
- Generate GeoJSON

_Open_ should open the box and give the option of opening 'My Maps' or 'Shared Maps', tabs in the same window (#design needed)
_Save a copy_ should save a copy of the current map. The user shouldn't be given the option of Editable or Snapshot and should just save in the same type
_Create Snapshot_ should ask the user to save the map first.

#### Notes from Design

> Screen 2 - Hovering over items should bring a grey box over the item, like in the burger menu already existing on the right hand side. Clicking should activate an item. (this is demonstrated on 'New')
> Hovering over 'Save As' opens a secondary pop out menu, where if you haven't 'Saved' your map for the first time yet, you can save as editable map. - You can also save the snapshot from here too.
> Clicking save should either, resave your map as an editable item if you've already saved it before, or only allow you to save as an editable map.
> Hovering over 'Open' opens a secondary pop out menu, where you can either 'open editable map' or 'snapshot' this should bring up a list of all 'editable maps' or 'snapshots'. You can then select an item and open as it currently does. Pressing on 'Editable Maps' from this secondary menu should open the modal pop out described.
> 
> Screen 3 is activated if you click on 'New'. All items will have this secondary pop out. List below...
> 
> New IF map hasn't been saved since things have changed: 'Any unsaved changes to the current map will be lost.'
> Buttons to read 'Cancel' or 'Ok'
> 
> New IF map has been saved. Pop out to say 'Are you sure you wish to open a new map?'
> Buttons to read 'Cancel' or 'Yes'.
> 
> Open modal list pop out with all editable maps already saved. "Sorry nothing saved yet", if they haven't saved before. - (IF a map isn't saved when they do this, to prompt them to save first)
> 
> Share to invite users via email, clicking should open modal pop out box like it currently does.
> 
> Export Shapefile to open modal pop out saying 'Are you sure you wish to export this?'
> Buttons to read 'Cancel' or 'Yes'.
> 
> Generate GeoJSON to open the same pop out that it currently does.

#### Additional Notes

Save a copy saves a map of the same name. It doesn't actually matter if the new map opens or the old map stays open since they are identical so go with consistency across the app. The modified date will distinguish the two to the user.

Create a snapshot IF the current map is not saved the user will be prompted 'Please add a title to save this map first'. Buttons to read 'Cancel' or 'Yes'

## Acceptance Criteria
- Implementation as per design and notes above. Where the notes and the design differ, the above notes are the point of truth.

**Comment by lin-d-hop** [comment]
@MelissaMc20 In the process of writing up this issue, alongside our conversations, I've made a few proposed updates to the design. Would you have a read and check if you agree, and more importantly any points you don't agree on? Thank you!

**Comment by rogup** [comment]
This can be tested, but before closing, @King-Mob will resolve the comments in the PR https://github.com/DigitalCommons/land-explorer-front-end/pull/176 separately

**Comment by MelissaMc20** [comment]
Sounds fine to me, I'm not particularly fussed about which way the 'open' works. The way you've described means less development as the current box for 'my maps' has this implmented already :) 

I think the Save flow you're describing also makes sense

**Comment by rogup** [comment]
@lin-d-hop @MelissaMc20 When creating a copy, could we rename it 'Copy of _', rather than just the same name? This would be very easy to implement. Whilst I'm testing it during development, it's a bit confusing because the My Maps list only shows dates, not times. And then when the map is open, it's not obvious which one I'm working on.

**Comment by lin-d-hop** [comment]
Agreed! Copy_of proposal is a good one. Thanks @rogup
