### ISSUE TITLE
Add Automated Testing to Deployment Pipeline

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#179]
## Description
Having unit tests is so much more powerful when the test suite is automatically run against every commit.
This is most likely best done with Github Actions

## Acceptance Criteria
- Setup Github Actions for LX
- Add running the test suite to the actions
- Update the wiki to explain how this works to support any future devs that might need to fix it.

**Comment by rogup** [comment]
Will copy mykomap's implementation https://github.com/DigitalCommons/mykomap/blob/master/.github/workflows/node.js.yml
