### ISSUE TITLE
Shared Maps not displaying

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#184]
**Describe the bug**

Shared Maps aren't showing up, My Maps are showing up in their place

**To Reproduce**
1. Go to Shared Maps
2. There won't be any, even if you have shared a map from another account

**Expected behaviour**

Maps that another user has shared with you via email should appear in Shared Maps. At the moment this doesn't work

**Screenshots/GIFs**

**Context (please complete the following information):**

**Additional context**

This is definitely a back-end issue, although there's a front-end hotfix designed to showcase the shared maps option on the Open map menu item

**Comment by lin-d-hop** [comment]
Agree this seems to be fixed. Love it when that happens :)
