### ISSUE TITLE
Mobile Responsive Title Bar

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#187]
## Description
Following on from #137 let's make the new title bar mobile responsive.

![image](https://user-images.githubusercontent.com/8669848/224776689-5b50756e-9e58-4dd2-a70b-84b92c484b1b.png)

## Acceptance Criteria
- Title bar looks and behaves well on all screen sizes

**Comment by King-Mob** [comment]
@lin-d-hop for the search bar on the smallest screen, when a user clicks on it, is that opening to the left, covering the map name?

**Comment by King-Mob** [comment]
@lin-d-hop it would make my life a lot easier if the map menu was to the left of the map name, like this:

![lx menu left of map name](https://user-images.githubusercontent.com/38507954/233999491-dfda9a29-7496-4556-8da0-c374ee00609f.png)

do you think this looks weird?

**Comment by lin-d-hop** [comment]
> do you think this looks weird?
What I dont like about this is that the most important nav button in the whole system basically disappears with two huge text bars. I'd like the search bar to be less prominent when not in use so the name bar and accompanying REALLY important tiny arrow is more prominent. WDYT?

**Comment by lin-d-hop** [comment]
> Suggest that we either limit map name length or set it to only go to two lines then you have to keyboard scroll to keep typing

Let's limit map name length. In the future if someone needs a longer map name for some reason we can explore other options.

**Comment by King-Mob** [comment]
@lin-d-hop I agree, so I have a collapsed version of the search bar that can be the normal state of it.

This is what I have now:
![collapse search bar](https://user-images.githubusercontent.com/38507954/234033865-059fe303-1db6-4550-ae77-b3115416f2a7.png)

**Comment by lin-d-hop** [comment]
I would say shrink the name bit to be the arrow and a few chars. Then any click on the name/arrow expands the name section out again.

**Comment by King-Mob** [comment]
Sorry, I was asking about expanding the search bar. This is what it currently looks like on medium sized phone screen

![navbar pixel5](https://user-images.githubusercontent.com/38507954/234035171-b1179513-86ad-4126-9a0c-c9ec1224a8ef.png)

**Comment by lin-d-hop** [comment]
Yes that's what I was answering:
Search bar small -> name big (default)
search bar big -> name small (go back to default when search bar clicked away from)

**Comment by King-Mob** [comment]
Gotcha, thank you!
