### ISSUE TITLE
Axios incorrect error handling

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/land-explorer-front-end#188]
I've spotted in a few places that we handle HTTP errors incorrectly when using axios in the front-end.

Unlike fetch, axios throws all non-2XX HTTP responses, but there are lots of instances where we check if response.status === 200 ourselves.

I'm not sure if the incorrect error handling is leading to visible bugs but we should fix it up to make sure.

https://stackoverflow.com/questions/49967779/axios-handling-errors

**Comment by King-Mob** [comment]
@rogup I found this in src/routes/changepassword.js 

`if ((response.status = 200)) {`

thought you might enjoy ;)
