### ISSUE TITLE
DEADLINE 10TH MAY: testing-lx.com domain expiring

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#193]
it's nearly been a whole year since we got our beautiful staging domain. At the moment it's managed under my account on namecheap. Do we want to:
* keep everything the same and renew for another year?
* transfer the domain to domains.coop ?
* use an entirely new domain for staging?

**Comment by lin-d-hop** [comment]
@King-Mob 
staging.landexplorer.coop now points to 65.21.108.119
staging.app.landexplorer.coop also points to 65.21.108.119
