### ISSUE TITLE
Prompt re-login if we get 401 bad token error from server

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/land-explorer-front-end#194]
**Describe the bug**
If something wrong happens to the FE client's JWT, or if the server's secret changes (which may need to happen for security reasons), the client stays logged in but the API calls silently fail.

**To Reproduce**
1. Login
2. On the server side, change the `TOKEN_KEY` in .env
3. Reload the server with `pm2 restart 0`
4. Try saving a map in the client. The post request fails but the user stays logged in.

**Expected behaviour**
When we hit a 401 error on the client side, we should log out (maybe displaying a reason such as 'session timed out') and prompt the user to log back in so we can authenticate properly.

**Comment by lin-d-hop** [comment]
Let's log everyone out on the release of #198 to resolve this
