### ISSUE TITLE
Accidentally removed share modal

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/land-explorer-front-end#203]
When making the UI changes to the title bar, we removed the Share Modal
https://github.com/DigitalCommons/land-explorer-front-end/pull/176/commits/300ce9de13e98b5ee4e3d9ed22160aac4dad4b60

But it's actually still needed, because you can share maps from the MyMaps list. This button currently doesn't do anything on staging.

**Comment by rogup** [comment]
@lin-d-hop @King-Mob Do you think we should add the modal back?

**Comment by lin-d-hop** [comment]
@rogup Sorry I dont understand. The Share button on the UI menu was deliberately removed and moved to the dropdown menu.

You are right to spot a regression on the share icon from MyMaps. This works on production so should be fixed on staging.

**Comment by rogup** [comment]
@lin-d-hop When we removed the Share button on the UI menu, we also removed the modal that lets you choose between sharing a shapefile vs GeoJSON, since you can choose these options directly in the dropdown menu

We need this modal if we want the share icon in MyMaps to work. Our options are:

1. Re-add the share modal and open this when clicking the MyMaps share icon
2. Add two different icons to the MyMaps list for either sharing a shapefile or GeoJSON, so we don't need to re-add the modal
3. Remove the MyMaps share icon altogether

1 seems like the best option to me. 3 is cheapest.
What do you think?

**Comment by lin-d-hop** [comment]
I vote 3. I think the 'share' option in that menu is superfluous. Opening a map before you share it makes intuitive sense to me.
