### ISSUE TITLE
User registration page is not mobile responsive

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/land-explorer-front-end#211]
The padding is all off when registering on mobile. Might be worth checking other non-mapp screens look okay on mobile too, given that we've done https://github.com/DigitalCommons/land-explorer-front-end/issues/187

**Comment by ms0ur1s** [comment]
Improved responsiveness and a general tidy up of the registration page.

**Desktop**
![image](https://github.com/DigitalCommons/allthethings/assets/22494228/9674738e-e1b2-444e-bffb-e594cb0d3337)

**Mobile - 1**
![image](https://github.com/DigitalCommons/allthethings/assets/22494228/901f2fda-90e7-4495-bd89-bb6e94340bc2)

**Mobile - 2**
![image](https://github.com/DigitalCommons/allthethings/assets/22494228/c3c2e2ad-1f7f-452b-a9ef-6bfb63fe6bab)

**Tablet**
![image](https://github.com/DigitalCommons/allthethings/assets/22494228/1191bf77-4eda-4f70-a69e-1ab60ca7bbf0)

**Comment by ms0ur1s** [comment]
Also made a few changes in the My Account area to ensure responsiveness. PR submitted.

**Comment by lin-d-hop** [comment]
Should this be on staging now @ms0ur1s @King-Mob?
It looks like this on my phone:
![Uploading Screenshot from 2023-07-21 09-37-13.png…]()

Still lots of padding and not a great use of screen space. What do you think?

**Comment by ms0ur1s** [comment]
Hi @lin-d-hop , that looks like the old version rather than the updated one, to me.

**Comment by lin-d-hop** [comment]
Well that's what I see on staging incognito.... can anyone confirm they see differently on staging?

**Comment by King-Mob** [comment]
@lin-d-hop sorry about that, assumed auto deploy was set up on development, will check it out in an hour

**Comment by King-Mob** [comment]
@lin-d-hop @ms0ur1s fixed, up on staging

**Comment by ms0ur1s** [comment]
Nice one @King-Mob

**Comment by lin-d-hop** [comment]
This is looking great!
