### ISSUE TITLE
Land registry polygons behave weirdly

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/land-explorer-front-end#215]
**Describe the bug**
If you click a land registry polygon, it adds the property to your map and highlights it in red. But you can click the same property again and it will add a duplicate, and highlight it again so it becomes darker red.

The overall behaviour is also clunky. It's difficult to understand which piece of land registry info corresponds to which polygon, once they've been added.

**To Reproduce**
1. Zoom in and enable the land registry layer
2. Click on a property and it gets highlighted and added to the info pane
3. Move the map and click on the same property. A duplicate gets added.
4. Add several properties and now it becomes very difficult to understand the land registry data.

**Expected behaviour**
Only allow a property to be added once to a map.
Clicking on a property should indicate which polygon we've selected (e.g. show a popup with the land registry info, or at least expand the corresponding data in the info pane. Only expand one property's data in the info pane at one time.)

**Screenshots/GIFs**
![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/48825436/44f1e2b1-0151-4edd-9bdc-4956ad97ddb9)

**Context (please complete the following information):**

**Additional context**

**Comment by King-Mob** [comment]
Some of the properties overlap each other, this is in the data, I'm not entirely sure what it's supposed to mean.

**Comment by lin-d-hop** [comment]
Thanks @King-Mob 
Seems outstanding issue here is more of a UX thing than a bug. Perhaps be move this to backlog with a 'needs design' label? Or is there something else in this to look at now?

**Comment by King-Mob** [comment]
Rereading this, point 3 is definitely a bug though

**Comment by rogup** [comment]
@King-Mob are you working on this too? I assigned it to myself and started working on it last week, but happy to hand it over if you've done more on it.

**Comment by King-Mob** [comment]
@rogup sorry, no I realise I'd misunderstood what the bug was
