### ISSUE TITLE
Snapshot / copy of map creates duplicates marker UUIDs

### ISSUE THREAD

**Issue by ms0ur1s** [DigitalCommons/land-explorer-front-end#216]
**Description**
Copying or creating a snapshot of an existing map causes duplicate marker UUIDs

**To Reproduce**
1. Create a new map
2. Add a marker
3. Save map
4. Create a copy / snapshot of the above map
5. The copied map includes markers with duplicate UUIDs

@rogup -  not sure if the steps are correct, please update where necessary.

**Duplicate UUIDs in database - supplied by  @rogup**

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/e76ab88f-2c3d-4eee-84c5-408014bf4d2a)

**Comment by rogup** [comment]
Note this affects polygons and lines too.

When we fix this, we should decide whether we want to fix the existing duplicates, or just let them be.
To fix, we could add a seeding script to generate and populate new UUIDs, then set a unique key constraint to the tables to prevent the problem in the future.
There's no harm in changing all the UUIDs in the backend, unless current front-end sessions are open, so would need to force a log out too.

**Comment by rogup** [comment]
Decided to just leave the existing duplicate UUIDs. The potential bug isn't that serious (editing the title/description of one object also changes objects with duplicate UUIDs.

We can reset all the UUIDs if someone complains about it, but it's a bit of a faff.
