### ISSUE TITLE
Password reset behaving weirdly

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#218]
**Describe the bug**
A few weird things noticed without rhyme or reason.

A user is having trouble with their link not taking them to the page to enter the new password: https://app.landexplorer.coop/app/my-account/password
Instead it takes them to: https://app.landexplorer.coop/auth

I was able to reproduce this by having multiple sessions open in my browser. I am awaiting confirmation from the user that closing all sessions helps. This info might also be a red herring.

**To Reproduce**
2. Have LX open in one tab
4. In another, logout and go to: https://app.landexplorer.coop/auth
5. Follow the password reset instructions
6. Clicking the link in the email does not redirect you to reset your password

**Expected behaviour**
When someone resets their password should they be logged out of all active sessions?

**Context (please complete the following information):**
 - Device: [e.g. iPhone6] Levono laptop
 - OS: [e.g. iOS8.1] Windows
 - Browser [e.g. stock browser, safari] Chrome
 - Version [e.g. 22] Production 24/5

**Comment by rogup** [comment]
@lin-d-hop I can't reproduce this.
Is it maybe a case of the updated front-end not being loaded on your browser? Does it work after doing a hard refresh (Ctrl + F5)?

If it's a case of the browser needing to reload its cached JS files, I think this is a general issue that we should try to solve, since it's come up before.

**Comment by rogup** [comment]
I've made a new issue to address the caching problem, since it's something we should fix in any case #219

**Comment by lin-d-hop** [comment]
> Is it maybe a case of the updated front-end not being loaded on your browser? Does it work after doing a hard refresh (Ctrl + F5)?

Confirming it was 100% not this. The reset worked for me most of the time.

**Comment by lin-d-hop** [comment]
Closing due to dev/test impasse

**Comment by lin-d-hop** [comment]
This issue has come up again. Reopening for notice
