### ISSUE TITLE
User locked out of their account

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#221]
**Describe the bug**
A user is locked out of their account. Details of the email if you message me in DM

**Expected behaviour**
The password reset behaves as #218 

**Context (please complete the following information):**
 - Version [e.g. 22] May release

**Additional context**
We need a few things.
1. We just need to get this user back in
2. We need a way for support people to help people get back in if emails fail, which they sometimes do

**Comment by King-Mob** [comment]
@lin-d-hop I've changed her password to the same as `test-lx@digitalcommons.coop` account, reminded what that is on element

**Comment by rogup** [comment]
Are they locked out because of the problem described in #218 (in which case, does a hard refresh solve their problem?) or is it something else?

**Comment by rogup** [comment]
It's difficult to work out next steps (other than the short term workaround of manually resetting their password, which John has done) if we don't know what caused the problem in the first place. 

- What was the actual text in their reset password email, in particular the link that didn't work for them?
- What's the link in the email that you see in your repros, and does hard refreshing not work for you either?

If we can't get answers to these questions, then I think we can close this issue, since there's no way to proceed.

**Comment by lin-d-hop** [comment]
This has come up again for another user. As before clicking the link takes the user to /auth instead of /app/my-account/password

Here is the email they received:

Dear Jane,

We received a request to reset your Land Explorer password. If you did not make this request, you can safely ignore this email.

You can reset your password by clicking the link below:

[https://app.landexplorer.coop/auth?email=jane%40farmgarden.org.uk&reset_token=08b91bed79118c5db47c11a59a6a95e85b27743182480722a2d9229744297a4871d8a2c2560f74e97339f7ab2c2c0e9f](https://u26502880.ct.sendgrid.net/ls/click?upn=43vDw9VMC8tRS4AUc9bDp-2BM-2BbUTP2aIqoMPFvQx5ZFERB-2FCHX2TmLwTAZOmWAOpxLfx3CIVymvow42Hq1cYXm07PcsHG1cCU4OQo2PBhQitHO3XT8bZA0FIyzsbMc3itDyQ-2FbTDsRRirwwTVPGBro664xg5kvCTXxM5VSf0dGDA2WcTEkksUcxW9ycpDi-2B7kcmxzhoTiZTlDrMHn0lwKp6K-2F2a0EXgU2oJMbY2MtZn3BaC0FG-2BFNvrtZnJY1fO1qLFGZ_GjpgnLzMZ8K0Gu9strJuJ9EwQ2lyEWJaHa1E960uYSpw3FiwnbBAWzPTXHlxfVcl1IVkD06cGyvrcpXtwpoWgxXyKFgzkCl1D9kRbhDKrLe0-2F5MRRgqS5nJlZL2Lx5EllvkBeUIttVtDRyeffGfTtBa0cBZNRJvEgVsxmk-2FfJnvW-2Fcg3S2Yiyvey-2B3YAWegc2J7TkGFf42vJJ-2BhVLrsrLg-3D-3D)

Please note this link will expire in 24 hours. After 24 hours, you must submit a new password reset request.

If clicking the above link does not work try copying and pasting it into your browser.
If you continue to have problems please feel free to let us know so we can help.

Many thanks,

The Digital Commons Team
