### ISSUE TITLE
Search bar behaves really badly when updating and deleting

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#222]
**Describe the bug**
Search bar behaves really badly when updating and deleting. It collapses inappropriately making it really hard.

**To Reproduce**
1. Enter something
2. Try to delete it or update it

**Expected behaviour**
I think it would be better to limit the fact that it closes to when you click again on the magnifying glass OR *if on mobile* when you click on the name.

**Screenshots/GIFs**

https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/71181536-4786-4990-b4d6-ab3d58fa2021

**Context (please complete the following information):**
- Seems to impact all devices, browsers, OS. May release.

**Comment by lin-d-hop** [comment]
Still buggy, even with the last PR:


https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/fef52035-0a5c-476e-af61-a5753d8a431c

**Comment by King-Mob** [comment]
@lin-d-hop is this still happening? can't seem to replicate

**Comment by lin-d-hop** [comment]
LGTM :pray:
