### ISSUE TITLE
[Spike] Choose WYSIWYG editor to use on LX description boxes

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#223]
## Description
To implement the new designs for marker/line/poly description boxes in LX we'll need the include a WYSISYG editor in the description boxes.

The editor should support:
- Image (and ideally video embed)
- H1 - H5
- bold, italics
- Links
- Blockquotes
- Horizontal Rule
- Ideally list items and ordered lists

## Acceptance Criteria
Perhaps this work has already been done by @ms0ur1s. If so let's just document it in this issue. If not, perhaps 2-3 hrs to:
- A comparison of a few popular options.
- A recommended options

**Comment by ms0ur1s** [comment]
[react-markdown-editors.docx](https://github.com/DigitalCommons/land-explorer-front-end/files/11786917/react-markdown-editors.docx)

**Comment by King-Mob** [comment]
@lin-d-hop concur with @ms0ur1s that react-markdown is the best option

**Comment by lin-d-hop** [comment]
Sweet. wizzy selecta :nerd_face:
