### ISSUE TITLE
[Spike] Mobile sweep of LX

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#231]
## Description
Much of LX hasn't been thoroughly tested on mobile. As a result there are areas of the app that are not mobile responsive and the experience is really bad.

In this issue it would be great to do a sweep of the app and create an ordered set of recommendations for improvement. Order in priority of your opinion of how critical the piece is for user experiece and joy. Add an estimate for the time required on design to each. 

Timebox this to 4hrs.... it doesn't need to be crazy detailed. Let's focus on what's critical rather than unpicking every last detail :)

## Acceptance Criteria
Make sure the sweep includes:
- Registration flow
- Login/Forgot password
- Drawing elements
- Viewing layers
- Viewing information
- Menu functions
- Searching
- My Maps and Shared Maps

Add a design time estimate for any recommendations that would benefit from a design before being implemented.

**Comment by ms0ur1s** [comment]
**Registration flow**
- Addressed in issue #211
**Login/Forgot password**
- Fine on desktop, tablet and mobile
**Drawing elements**
- All fine
- Read only on mobile
**Viewing layers**
- Markers all good
- Polygons all good
- Layers all good
- Although there is double tap for zooming in (handheld device), pinch zoom would be nice (is expected?)
**Viewing information**
- Would be nice if selected item automatically centred (mobile)
**Menu functions**
- Difficulty swiping upwards to menu items - works intermittently (Land Data, mobile)
- Tool tip remains open when slide out opens / same with all tooltips if you open and close using the buttons on the nav (Land Data, mobile)
- slide out and user specific menu can be opened simultaneously - opening one should trigger close of one on mobile (tablet / mobile)
**Searching**
- When initially selected, only the letter E is visible (mobile)
- Smaller screens can't see what you're typing into the search box (mobile) 
- mobile - X to clear looks a bit janky (mobile)
**My Maps and Shared Maps**

**Comment by ms0ur1s** [comment]
1. **Search** - 1-3hrs
2. **Menu swipe**  (Land data) - 2hrs (?), not 100% as requires investigation
3. **Overlapping menus and close when tap / click off** - 2-3hrs
4. **Pinch zoom** - (?hrs) Not sure requires investigation - could be something as easy a mapbox setting
5. **My maps mobile view** - 1-2hrs

As with all estimates, it could be more or it could be less 😁

**Comment by lin-d-hop** [comment]
New epic with all of these issues created:

https://github.com/DigitalCommons/land-explorer-front-end#workspaces/megaboard-639bb01fc526ef0010ab662b/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQ0MDAw?state=OPEN&state=TODO&state=IN_PROGRESS&state=CLOSED

PS Zenhub has really gotten shite recently. These 'improvements' haven't happened on my other projects :(
