### ISSUE TITLE
Implement New marker Designs

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#233]
## Description
New marker dialogues have been designed here: https://xd.adobe.com/view/648e9731-3e23-49ca-af36-392065803fd1-31dd/screen/40651043-5839-4db2-8c5e-4fdbb019eaa3

https://xd.adobe.com/view/2f2fa6bb-d491-4de0-8784-383c23442dff-7a7c/grid/

Plus new layer and map saving dialogues here: https://xd.adobe.com/view/690fc910-3dad-4c7d-920f-621848a14038-3c5c/screen/75e0ba56-d099-43a4-b733-6b4f88887654

## Acceptance Criteria
- New designs implemented for dialogue boxes
- Unit tests where possible
- Dialogues are functional for lines, markers, polys
- No change to info box currently
- Editing works as now. No markdown rendering included yet. No WYSIWYG for input.
- All buttons - close, edit, linked maps, add to map - are functional as per now.

**Comment by lin-d-hop** [comment]
This is looking really great and a huge improvement.

Perhaps a couple of points we can chat about in the meeting today:
- Is it best practice to have the markers the same size regardless of conent?
- Is horizon orientation best when the most variable length content is the description?
- Is having the buttons at the bottom left aligned the best positioning?

**Comment by lin-d-hop** [comment]
Great. Shall we make some small tweaks?

1. Vertical orientation as the default? Then formatting in the best way to display images. Would thsi work?
2. Shall we try right align for buttons? This might be best regardless of orientation.

**Comment by ms0ur1s** [comment]
@lin-d-hop, as I've slightly adjusted the width centred seems more appropriate. What do you think?

**Centred**

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/177bc96c-dbbc-4c53-b2e3-213fc10d6ece)

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/02bcdefe-776e-4f00-baf4-cd8807880c2d)

**Right aligned**

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/62ebc791-054d-4f0d-9303-dd5a3f37751d)

**Comment by ms0ur1s** [comment]
Will push final commit and PR, once we've decided.

**Comment by lin-d-hop** [comment]
@ms0ur1s These updated designs look great. 
If you've built this then yes please do commit :)
