### ISSUE TITLE
[LX] Improve My Maps mobile view

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#237]
## Description
In #231 it was identified that the My Maps view on mobile could be improved.

## Acceptance Criteria
- Design improvements to the My Maps view
- Implement these designs 

Estimate on this was 1-2 hrs so feel free just to dive in and not overthink it. I assume we're just going for quick wins here.

**Comment by ms0ur1s** [comment]
Another one that seems to have been fixed by previous work in the pipeline.

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/987c763a-8e87-48fc-9c17-cc2b22c45689)

**Comment by lin-d-hop** [comment]
Awesome! Easy :)
