### ISSUE TITLE
Update link to privacy policy

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#242]
**Describe the bug**
During the registration flow the the Privacy Policy link is broken. This needs to be fixed

**To Reproduce**
1. Log out and hit Register
2. Click on the Privacy Policy link
3. See error

**Expected behaviour**
You should see a pdf of this doc:
https://docs.google.com/document/d/14tc9m_bC4LL1CaKuNeaneExixWsOa8d27JJjI8h2LeA/edit

**Comment by ms0ur1s** [comment]
@lin-d-hop, should this document be hosted on sharedassets.org.uk?

**Comment by lin-d-hop** [comment]
nope. Probably should be hosted on the local server?

**Comment by ms0ur1s** [comment]
Cool are you ok with me renaming the pdf to just privacy-policy as in the twine example?

@King-Mob, is it ok if this lives in the public folder of the LX codebase?

**Comment by King-Mob** [comment]
@ms0ur1s slight hesitation just on file size. it seems like this could easily be a webpage? is there a reason it needs to be a pdf? @lin-d-hop

**Comment by ms0ur1s** [comment]
Cool @King-Mob, current file size is 78kb

**Comment by ms0ur1s** [comment]
I'll wait for @lin-d-hop to respond before progressing.

**Comment by lin-d-hop** [comment]
It doesn't have to be a PDF. We could make if a public pdf on the GDrive. But is 78kb really a concerning file size?

**Comment by ms0ur1s** [comment]
Will go with the PDF, for now, and we can knock up a page if / when necessary.
