### ISSUE TITLE
[Backsearch] Add license and disclaimer to info panel

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#250]
## Description
We need to display the following licence information when displaying info from Land Reg on the Info Panel:

> Information produced by HM Land Registry. © Crown copyright [INSERT DATE OF LAST LAND REG DATA UPDATE]

We also need to state that this information is displayed for 
> Some data is displayed here for evaluation purposes only. For more information [click here.](landexplorer.coop/land-ownership-how)

click here should redirect to: landexplorer.coop/land-ownership-how 
[Issue #12](https://github.com/DigitalCommons/land-explorer-static/issues/12) has been created to set up the redirect.

Marcel has created a great design for this. Let's extend it with the evaluation disclaimer.
![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/b16473d4-0bff-4bbf-b832-cf8ca8d0da17)

## Acceptance Criteria
- License and evaluation disclaimer added when property info displayed on the Info panel
- Each property in the info panel has the info displayed when expanded.
- Year accurately reflects the last update that we have downloaded. If this is not yet possible let's hard code it and come back as tech debt.

**Comment by lin-d-hop** [comment]
A good one for you @ms0ur1s, but check in with @King-Mob to figure out the best way to accurately display the year :)

**Comment by ms0ur1s** [comment]
@lin-d-hop , placeholder added.

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/66f93b88-c6cb-4340-b2c4-f5a3ae8dc337)
