### ISSUE TITLE
Implement FE Functions for LandReg Back search

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#256]
## Description

We wish to implement the first stage of the Land Reg back search. 

At a high level:
- User clicks 'View proprietor's other properties'
- FE sends a request to BE: GET landexplorer.coop/api/search?proprietorName=Cambridge;
- BE sends a request to Property Boundaries service: GET propertyboundaries.landexplorer.coop/api/search?proprietorName=Cambridge;
- Data flows back to FE in the same format as the existing property data.

~@King-Mob will you confirm the URL for the backend request please?~

FE Designs:
![Screenshot from 2023-10-28 18-20-04](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/88d61cab-d1a6-47e2-b65a-315810263850)

## Acceptance Criteria
As per designs:
- A button is added to any property that has proprietor information saying 'View proprietor's other properties'
- FE queries BE with the proprietor name (this can be mocked for now if necessary)
- The list of proprietors properties appears in the same info panel, using the styles from the designs.
- In the case that the proprietor has no other properties we only see the selected property in the list
- In the case tha the proprietor has other properties we see a list with checkboxes. Implement to the designs eg 'Select all' 'View other properties'
- Use can select a set of properties to view.
- Once the user has selected properties and pressed 'View x selected properties' these properties are higlighted on the map.
-> **Question**: can we then frame the map around the selected properties so we can see them all highlighted?
- When a user clicks on the property in the list they enter the detailed info panel for the property. 
-> **Question**: What is the map behaviour when this happens? @ms0ur1s perhaps we need a call to chat this through?

**Comment by lin-d-hop** [comment]
@ms0ur1s This needs to bump up to a priority now please

**Comment by King-Mob** [comment]
@lin-d-hop back end is just landexplorer.coop/api

**Comment by lin-d-hop** [comment]
Note to me: Move to #253 when we solve #zenhubfail
