### ISSUE TITLE
Error loading My Maps

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/land-explorer-front-end#257]
**Describe the bug**
When I attempt to load my maps I see the following error.

"There was an error loading maps."

**To Reproduce**
1. Log into my LX account 
2. Click on My Maps
3. See error message

**Expected behaviour**
I should see a list of my maps

**Screenshots/GIFs**
https://www.awesomescreenshot.com/video/22225831?key=9bee39d68086764514e73655f33d7040

**Context (please complete the following information):**
 - Firefox on Windows

**Comment by lin-d-hop** [comment]
Fixed with #190
