### ISSUE TITLE
Multiple copies of the same piece of land

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/land-explorer-front-end#258]
**Describe the bug**
When viewing the land ownership layer it is possible to select they same piece of land more than once.

**To Reproduce**
1. Open LX and enable Land Registry data layer
2. Zoom into level where land ownership polys are visible.
3. Select a piece of land. See it selects. Select again. No change. Zoom in a level. 
4. Attempt to select the same piece of land by clicking on it. 
5. Two copies of the poly have now been selected. 
6. It seems you can do this again once, each time you change the zoom depth.

**Expected behaviour**
It should not be possible to select the same piece of land one than once.

**Screenshots/GIFs**
https://www.awesomescreenshot.com/video/22226359?key=628a13b88f86233bdfe080934803543c

**Context (please complete the following information):**
 - Firefox on Windows

**Comment by lin-d-hop** [comment]
This is now fixed on prod after yesterdays release :)

**Comment by ColmDC** [comment]
I confirm I can no longer replicate the bug. :-)
