### ISSUE TITLE
[Backsearch P1] [Ownership panel] Select and deselect all links

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#264]
[EDIT]

Clear all is implemented, though let's think about the UX here as it is not quite right.

Select all still to be completed.

## Updated acceptance criteria
- 'Select all' link that selects all of the properties as if a user had clicked on them all.
- Error handling in the case that 'Select all' creates an action too large for the server to handle.

Probably we'll make new issues for this work.... but moving this back for now

___________________________________________________________________________

### Description
After a chat this morning we've identified a set of UX improvements that will improve the Ownership Search panel.

The updated designs have a 'Select all' already, so let's work to this.
We want to additionally add a 'Clear all'. I'm not sure how these should align with each other, but let's work to something that will still be mobile friendly :)

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/d6696704-964c-4762-abed-11745d6111ed)

### Acceptance Criteria
- 'Select all' link that selects all of the properties as if a user had clicked on them all.
- 'Clear all' link that clears all ownership search. 
- 'Clear all' should also deselect the properties. This will mean that these properties are also no longer appearing in the 'Land Information' panel. If there are other properties selected in the 'Land Information' panel that don't pertain to the current 'Land Ownership' search then they should remain.
- When there are no properties in the ownership search then after the user closes the panel the 'Ownership Search' icon should disappear from the tool bar.

**Comment by ms0ur1s** [comment]
Updated image to match current iteration of the ownership search

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/99aa1f13-6ed8-4976-b764-9f100f9ca193)

**Comment by ms0ur1s** [comment]
`height: 16px` in above design

**Comment by lin-d-hop** [comment]
Select all on large datasets gives the worst possible experience. White screen of death and you have to totally refresh the page.


https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/9f246698-e9e7-4bef-a27a-2f14155fa135

**Comment by ColmDC** [comment]
Select All Currently Visible in the List would also not be very useful atm, as there is currently no geographical coherence to the order they appear in the list. We would need to support that first. See #279 for thoughts on this.

**Comment by lin-d-hop** [comment]
@rogup @ms0ur1s Let's uncomment this for testing with the error messaging issues :)

**Comment by rogup** [comment]
Added the select all button and ready for QA. (I didn't send for review since it was literally just uncommenting one line of code)

**Comment by lin-d-hop** [comment]
@rogup has this been deployed to staging? I couldnt see the box just now...

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/0d7e0047-3eca-4e59-9b47-df18c8c75419)
