### ISSUE TITLE
[Backsearch] Draw temporary arrow between primary and 'next' property in Ownership Search panel

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/land-explorer-front-end#280]
## Description
While the user hovers over a Go to Property arrow, display an arrow from either the centre of the map towards that property, or from the current centre of the map towards that property. Explore different types of designs for the arrow to give sense distance, that works consistently whether the property is off or on the map, and also if it is very close. 

## Motivation
Clicking on a Go to Property arrow, can pan and zoom the map great distances in unexpected directions, it would be to have visual cue as to where that property was relative to the last selected property, or perhaps the current centre of the map. 

## Acceptance Criteria
Users have a reliable visual clue as to where the property is before deciding to zoom and pan to it.

**Comment by lin-d-hop** [comment]
I dont think this is a well specced issue. This needs design and the issue proposes a solution that feels inappropriate to the problem.

**Comment by ColmDC** [comment]
> This needs design 

That's why I put it in the Design backlog.

>and the issue proposes a solution that feels inappropriate to the problem.

I guess that would have been identified by the desinger.

Where would be the appropriate place to respond to your points or discuss the design idea?
