### ISSUE TITLE
[Backsearch P1][Design] Collect user feedback in app

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#288]
## Description
Some background research has been done in #70 

The feedback we want to collect should be based on [this form](https://docs.google.com/forms/d/e/1FAIpQLSegql4aJlQLtKXBMZshxDgdDBq_SVlv8wTy8eSKabo1gVfVVA/viewform). Note it can actually be that form if you like.

It is important that:
- All users see that there is a place to offer feedback. But we dont want to annoy people with it. Perhaps a pop up on their first visit once the feedback tool has been added and an animation as it minimises to an easy to find place....
- Additionally, we want people who use the Land Reg layer to be particularly clear about why it is important they tell us how they are using this data. It would be good to remind people, perhaps once per session after x mins of using the land reg search. It should be simple to give us this info, and say why we want people to tell us eg

_LandExplorer believes land ownership data should be easily publicly accessible, so we are collectiving information on how and why land ownership data is helpful to you, your community and your work. Please let us know how you are using this data_

As you can tell from reading this I am not clear on how this should work. Perhaps it would be good to chat about it @ms0ur1s?

## Acceptance Criteria
- Clear designs enabling and encouraging user feedback in app
- Specificity about how we should ask and remind people to balance getting the info without annoying folks off.

**Comment by ms0ur1s** [comment]
Cool, @lin-d-hop I'm happy to chat whenever you're free.

**Comment by ms0ur1s** [comment]
As well as the suggestions that accompany the proposed designs and functionality, it might also be useful considering the below when addressing user feedback: 
* sending an email invite to the LX’s existing user base to participate in an online survey regarding the app. As well as eliciting feedback on specific issues, mentioning new features might re-engage lapsed users
* creating a discussion group within the LX repo on GitHub, to allow users to participate in more in-depth conversations with app owners / maintainers about the app’s usability, bugs and new features. This could open a can of worms, but direct contact between app owners / caretakers and app users could also prove valuable.
* creating dedicated bug reporting page on the LX website, where users can easily highlight any issues discovered while using the application. This would a guided form with options for type of issue etc and fields for explanations and steps to reproduce. A ‘User Issues’ link could be added to the app menu or user menu. After initial contact perhaps a discussion could be initiated, as above. 

### General LX feedback form
For general feedback, I have proposed the addition of a tab to right of the map boundary, above the map controls. The tab is visible, yet not distracting or obstructive. On handheld devices the tab could either shrink, be displayed as an icon only, or join the map control buttons (respective designs are included). By clicking / tapping the tab, the feedback form could either slide in (and perhaps simultaneously fade in) from the bottom or the side of the screen, and come to rest in the centre. Alternatively, the form could slide in from the side along with the tab, with the right side of the form remaining attached to edge of viewport. After submission the tab could remain visible, as its inclusion does not affect usability, or be hidden for the remainder of the session.

The form would appear full screen on handheld devices, with perhaps the app’s top bar visible. The cancel and submit buttons would be fixed within a container at the bottom the screen, so the form itself can scroll behind them. To inform the user that further questions appear below the viewport’s boundary, a circular blue button would sit atop the cancel and submit container, and lightly pulse.

The form used is simple, clear and based on the Google form mentioned in the initial issue, though the explanatory text at the form’s head might benefit from some condensing.

**Desktop Variant 1**

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/abffb5f7-dd56-487d-b31f-07b897f28eaa)

**All designs for this form**
https://xd.adobe.com/view/4b3e141d-7a00-4718-a747-4e760028f2b1-1e6d/
</br>

### Ownership Search specific feedback form
Unlike the general LX feedback form, there would be no call-to-action (CTA) required to trigger its appearance. Rather, this form would slide up from the bottom right of the viewport, X amount of time* after the user closes the Ownership Search panel – perhaps all left hand panels should also be closed (?). This form is more succinct than the general feedback form, encouraging comment on this specific tool. Once visible the form does not consume much screen real estate and can easily be closed – whether the form is hidden for the remainder of the session after closing, or reappears after a specific lapse of time, is up for debate. Also, if there is no interaction with the form after a proscribed amount of time, it would slide off screen and reappear after the next interval. 

On handheld devices, where screen area is limited, only the head of the form would appear at the bottom of the viewport, topped by a green CTA containing an up arrow. Once tapped the whole form would slide into view, with the up CTA becoming a down button, allowing for the form to be minimised if not closed or submitted.

**Desktop Variant**

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/2291703e-b334-4960-8dce-eb1f472b18a5)

**All designs for this form**
https://xd.adobe.com/view/cdc790e0-8127-425c-9ba3-39256b82db77-9894/
</br>

### Feedback / survey prompt
This dialogue would appear when a user is about to leave the app, and would sit in the middle of the screen. It could either be used to prompt the user to complete the feedback form or redirect them to another page. It would not prevent the user from leaving the app, only act as visual cue to encourage user interactivity. 
      
**Desktop Variant**
                      
![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/6e2e9f75-88d3-448c-8676-8c12e5a6c9ce)

**All designs for this dialogue**
https://xd.adobe.com/view/15bd2612-6b9b-4581-bd87-21b1bc1fa8a9-40ee/
</br>

*This time should be based on analytics relating to the average user duration on the app. In general this data, along with heat maps and session records if available, should be used to aid the improvement of user experience.

**Comment by lin-d-hop** [comment]
Thanks @ms0ur1s these look great!!

Some suggestions on my side:

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/e0bed190-64d1-4dde-890f-3b4c2d8375bb)

This looks ideal I think. If people want to write lots I think it would be good to support that. Can we make the text boxes paragraph size rather than line size? On mobile this might mean pagination? Or maybe on mobile just one line?
I think the last question is repeated, so removing that should help make space

I don't think we need the second feedback form. The whole point is to get the detailed information about how people are using the LandReg search so that we can make a case. Its not about improving the tool but about collecting stories of why it is important and useful to make this info public.

So the popup should say the same text as the main form, with yes no buttons. Then if they click yes the main form pops up.

Does that make sense?
Would you redo the designs taking these little bits into consideration?

Thanks!

**Comment by ms0ur1s** [comment]
Thanks for the feedback @lin-d-hop and @kateswade, I'll amend the designs based on your suggestions.

**Comment by ms0ur1s** [comment]
Hi @lin-d-hop and @kateswade, amended versions including animation, below.

### Desktop Screen
Once you've navigated to the page below, click anywhere on the image (or on the feedback tab, to simulate real world use) to to view form animation.

https://xd.adobe.com/view/70053b22-9ad6-47fc-8ea0-7271542b4f3f-2556/


### Mobile Screen - scrolling
As above, click anywhere on the image (or on the blue CTA above the submit button, to simulate real world use) to view the scrolling animation.

https://xd.adobe.com/view/45a47a3b-37af-42a2-b551-e6684d35e397-10f7/


### Mobile Screen - paging
As above, click anywhere on the image (or the green arrow above the submit button, to simulate real world use) to view the paging animation.

https://xd.adobe.com/view/fcd7a265-2f01-4f67-9a38-d8afa84bdef9-a984/

### Feedback prompt - with desktop form flow
As above click through as if to simulate use. After the last screen there is a short pause and then journey begins again.

https://xd.adobe.com/view/567210fa-a67e-474d-aa56-2be403a4f1ca-0321/

**Comment by kateswade** [comment]
Thanks @ms0ur1s, to my untrained eye these look great! is there any paricular feedback that would be helpful?

**Comment by ms0ur1s** [comment]
Hi @kateswade, thank you. Honestly, anything you think might improve or impede your experience as a user. Not totally straight forward, I know, as what you've got to work with is only interactive on the most basic level. But you probably get my drift 😄.

**Comment by lin-d-hop** [comment]
Hi @ms0ur1s 
Thanks for these!

A couple more notes on the designs and we'll be ready to kick off:

1. Can the animation of the feedback form popping up come from the Feedback button on the RHS? Doing the animation in this way indicates to the user how they can access this if they decide to feedback later.
2. The mobile design leaves the submit button visible while the last questions are hidden. The result of this will be that people never do the last questions on mobile. My preferred design would have a 'Next' then a 'Submit' as the buttons. I guess a type of pagination. What do you think?
3. Can we add a 'Don't show this again' check box on the autopop up?
4. Lastly I'd like to update the text:

Wording on the pop up when Land Ownership is turned on:
We believe that information about land is powerful, and can help people and communities to create real change. By letting us know how you are using LandExplorer we can make a stronger case from more data to be made public and available for everyone. Will you take a moment to tell us how LandExplorer is helping you today?
Buttons: Maybe later ...... Sure!

Wording at the top of the form:
We believe that information about land is powerful, and can help people and communities to create real change. By letting us know how you are using LandExplorer we can make a stronger case from more data to be made public and available for everyone.

We'll use this information to improve LandExplorer, gain support for our work and campaign for publicly accessible data. We will ensure that you and any groups you refer to remain anonymous unless we gain your express permission via email. 

Questions:
What is LandExplorer helping you to do today?
What impact can this have for you and your community?
Who will benefit from this?
What would make LandExplorer even better?

Thankyou:
Thank you!

**Comment by ms0ur1s** [comment]
Hi @lin-d-hop, updates requested are below. Give me a shout if I've missed anything.

### Desktop version with amends
https://xd.adobe.com/view/1112be9f-1a2d-4e56-9cb3-d5136938a2e7-4441/

### Mobile version with amends
https://xd.adobe.com/view/fcd7a265-2f01-4f67-9a38-d8afa84bdef9-a984/
