### ISSUE TITLE
Shapefile Data Export

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#29]
## Description

RGS require that their map data (lines, polys and markers) can be downloaded in Shapefile format.

## Acceptance Criteria

- From the 'Share' icon within the UI the popup offers an additional option to 'by Download' (design needed). The only option is Shapefile format as a .zip.
- When button clicked a file of  is begins downloading
- The downloaded .zip will contain a .shp, .shx and .dbf files as the minimum files needed for Shapefile.
- The file contains all the lines, polys and markers of the current map.
- The map must be saved before it can be downloaded (just like with sharing).
- In Shapefile entities can have attributes. It would be good to provide feature parity to the LX UI:
-- Markers will have attributes: Name, Longitude, Latitude
-- Lines will have attributes: Name, Length
-- Polys will have attributes: Name, Perimeter, Area (km2, ha, acres)

## Additional Bits

I expect that the best way to do this will be to use the GeoJSON and then convert to Shapefile using an existing package. Something like [this](https://github.com/jdesboeufs/geojson2shp) might help us?

**Comment by King-Mob** [comment]
Seems to work for me now, version is up on staging @lin-d-hop

**Comment by lin-d-hop** [comment]
I explored the Shapefile in QGIS and it appears to render the markers as expected and includes the name and description text as intended. Excellent work :tada:
