### ISSUE TITLE
[Spike] Write permission when a map is shared

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#304]
## Description

Currently when a map is shared with another LX user the additional user has permission to View the map in read only mode.

Lots of users want to be able to share a map and have the map be editable. As part of the Oxon work on Collab Mapping I want to enable a shared map to edited by the person with whom it is shared. Currently the user just had read-only permission. 

The point of this spike is to land on a reasonable step to enable this. Some options:
1) We change the shared permission to be able to write on the original map. Ensure this user cannot delete the map. Is there anything in current data structures that makes this tricky?
2) We change the 'Share' options to be able to share and give 'Read' or 'Write' permission to the new user. This will take some design as well let's assume a design similar to when sharing a google doc. Would it be sensible to go this extra step for any reasons?

<img width="622" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemJPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9696c64029d5fc26d43e56062efb1604a18f5e80/Screenshot%20from%202024-01-16%2015-57-11.png" alt="Screenshot from 2024-01-16 15-57-11.png" />

## Acceptance Criteria

A proposal of the simplest way to achieve enabling Write permissions on a shared map with an estimate of how long it would take in dev time.

**Comment by rogup** [comment]
Notes from our call: https://docs.google.com/document/d/13EQhZPoMtTPcvae7T-joA-GPl4fdBJjmH61UzTw_GZY/edit#heading=h.dkhs6ct5tzyy
