### ISSUE TITLE
[LX Collab Mapping] Read, write, own map permissions

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#307]
**Please track under the clockify project [LX Collab Mapping]**

## Description

Following on from #304 
Currently users can own maps that they create. They can share these maps as read-only with other users.

We want to implement three levels of map permissions:
Read - as per the current read only, the user can see the map and interact with elements but cannot add or edit the map
Write - the user can see the map, interact, add and edit elements on the map.
Own - as per the current owner. Can write. Can also delete the map and share the map with other users.

Additional complications arise with write are explored in #306, which is likely a prerequisite for this piece.

## Acceptance Criteria
- Three potential permission levels exist on maps.
- The access granted with each permission level is as described above.
- ~Unit tests as standard~
-

**Comment by ms0ur1s** [comment]
![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/213b90ee-6ec0-4bfe-b7fd-01d89503a59f)

**Comment by ms0ur1s** [comment]
![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/39bb0440-ba69-4e45-9e61-143ba74c769a)

**Comment by lin-d-hop** [comment]
@ms0ur1s How's this work coming along?
Will be great ot be new and improved map sharing online :)

**Comment by ms0ur1s** [comment]
> @ms0ur1s How's this work coming along? Will be great to be new and improved map sharing online :)

Hi @lin-d-hop, apologies, as with #308 the hold-up is #306 which I'll organise to Rohit so we can resolve it.

**Comment by rogup** [comment]
@ms0ur1s are you creating a UI for a map owner to assign either write or read permissions to another user? It's not clear whether this is in the scope of the issue

**Comment by ms0ur1s** [comment]
Hey @rogup, yep that was done in either #306 or #308.

**Comment by rogup** [comment]
This work will be done within the PR linked to #306
