### ISSUE TITLE
[Social Farms & Gardens-Spring-24] A colour palette for Social Farms and Gardens markers

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#309]
**Please track under the clockify project [Social Farms & Gardens-Spring-24]**

## Description
Social Farms and Gardens have the 'Resilient Green Spaces' data sets in LandExplorer. Currently each of these data sets use identical markers. They have requested we change these colours.

I would like to propose a simple colour pallete for them for approval before we implement.

On implementation I think additionally we make the dot inside the on/off toggle the same colour as the marker so that it is clear in the UI which colour represents which set.

![Image](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/e8d778d4-15a4-4816-b9f3-be54710d3715)

## Acceptance Criteria
- The pallete needs 5 colours. So 5 marker icons in these colours such that we can sign them off.

**Comment by ms0ur1s** [comment]
Hi @lin-d-hop, a variety of colour sets are included below.

https://xd.adobe.com/view/bc683f6a-8c40-49d1-85d8-c60932251927-e93b/grid
