### ISSUE TITLE
Ownership Search: Related properties not highlighting on map

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#311]
**Describe the bug**
When using the ownership search to see related properties, the properties aren't highlighting on the map. And clicking on one property selects all of them.

**To Reproduce**
1. Turn on ownership search
2. Select green property
3. Click 'check for other properties'
4. Click arrow next to one of the properties
5. Click clear all, then click one of the properties in the list

**Expected behaviour**

1. The properties highlighted in green should display on the map
2. The properties should only be highlighted in green if they have been clicked on

**Screenshots/GIFs**
![lx bug property selection](https://github.com/DigitalCommons/land-explorer-front-end/assets/38507954/577babc1-9cd3-4482-879e-539da57e0565)

**Context (please complete the following information):**
 - Device: desktop
 - OS: windows 10
 - Browser: chrome
 - Version: 123

**Additional context**
I checked to see if this was happening on my local version of the front-end. I haven't pulled from dev since I left the project. Connecting my local version to the staging back-end, this bug doesn't appear.

**Comment by lin-d-hop** [comment]
Strange that this has started failing in between a deployment. That is likely a clue...

**Comment by ms0ur1s** [comment]
Also, the Ownership Search panel remains populated when the Land Information panel has been cleared. I can't remember whether that's expected functionality, though.

https://www.awesomescreenshot.com/video/28988449?key=2c3e132d4873a7804fa706e8cfc49ae4

**Comment by lin-d-hop** [comment]
Let's leave this for now. I've noticed it in the past but it's a bug with a very easy work around.

**Comment by ms0ur1s** [comment]
Related pull request below
https://github.com/DigitalCommons/land-explorer-front-end/pull/323
