### ISSUE TITLE
[Social Farms & Gardens-Spring-24] Add colour options for data groups

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#313]
**Please track under clockify project [Social Farms & Gardens-Spring-24]** 

## Description

Following on from #309 we want to implement  these designs such that 'Data Groups' can be assigned a colour code. 

Design: https://xd.adobe.com/view/bc683f6a-8c40-49d1-85d8-c60932251927-e93b/screen/c0d8a0ea-7d06-475c-8785-808f0d73d77e
Colour set 4 was chosen.

As there are just 5 colours to choose from, we can create the assignment of the colour in the DB in the way that feels most appropriate - the hex, or just a number 1-5, or something else. Up to you.

When a colour is associated with a data group we should see a UI change in two places:
1. Any marker/poly/line that is a member of that data group should have the marker itself, the line and poly border line and the info box render in the associated colour. Note that there are not design examples for the lines and poly border lines.
2. The on/off toggle should display in that colour when turned on, as per designs.

![Screenshot from 2024-03-27 13-06-24](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/3292ff5a-e125-4b32-9e74-da32df12b0f4)
![Screenshot from 2024-03-27 13-06-12](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/846c4643-f749-4c8e-8757-8cc0782cfa1f)

## Acceptance Criteria
- Two UI changes as specified above
- If a marker/poly/line is moved to another data group, its colour should change accordingly.
- The default marker colour remains the same. 
- Any data group without a specified colour should render in the default colour.
- Currently when markers/lines/polys that are drawn are selected they change colour, and when markers/lines/polys that are part of data groups are selected they do not change colour. Let's keep this behaviour.

**Comment by ms0ur1s** [comment]
![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/0b100e47-9000-4135-950a-598e19debc73)
