### ISSUE TITLE
[Social Farms & Gardens-Spring-24] Adding to data layer endless loading

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#314]
**Describe the bug**
We added the feature to add a marker/poly/line to a data layer.

On attempting to use this feature I just get an endless load.

**To Reproduce**
1. Go to a marker/line/poly
2. Click on 'Add to Map'
3. Change to 'Data Layer' panel
4. Click on a Data Layer you have access to to add the marker/line/poly to the layer
5. See the endless spinner

This marker has a name, so I'm wondering if the fact it is 'undefined' is relevant here. Same happens for lines/polys, named and unnamed.

![Screenshot from 2024-03-27 16-36-52](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/a8a52e21-4738-4909-9f31-f171d748621c)

**Expected behaviour**
The marker/line/poly should be added to the appropratei data layer, and thus I can view it from any account with access to that data layer.

**Context (please complete the following information):**
 - Device: desktop
 - OS: ubuntu latest
 - Browser: chrome

**Comment by ms0ur1s** [comment]
@lin-d-hop tested this locally and added a test group to staging to test current published development version and all works perfectly now. Solved in #313, video included below.

https://www.awesomescreenshot.com/video/26994377?key=5b67e0e7f0ebd3dd028b0ec788eab0e0
