### ISSUE TITLE
[Social Farms & Gardens-Spring-24] Reload map on refresh

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#316]
**PLease track time for this bug under 'Social Farms & Gardens-Spring-24' on clockify**

## Description

When you refresh on LX the UI reloads to a new and unsaved map. As we develop more features around the map as document tools users will increasingly be using saved maps and thus a refresh in this way is annoying. It would be great to refresh and reload the map that the user is currently editing.

From Rohit on Element:
_I think this would be quite easy to do (about 1-2 hours work), by saving the current map ID in the browser's sessionStorage, which persists over site reloads but then gets wiped when the tab is closed_

## Acceptance Criteria
- When a user has a saved map open and they press refresh, the map is reloaded and reopened to the last saved state.
- If the user is editing a unsaved map, a new map is reloaded as per the current behaviour

**Comment by ms0ur1s** [comment]
Ready for review. Thanks @rogup, the only difficulty I encountered was forgetting the sessionStorage variable is saved as a string, when comparing it to mapId  😅.

https://www.awesomescreenshot.com/video/27109423?key=3e34378d16d4e7279feb08028f0d9c09

**Comment by lin-d-hop** [comment]
Tested a few different maps and actions.
LGTM :)
