### ISSUE TITLE
Update 'User menu'

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#320]
**[ Social Farms and Gardens ]**

## Description
The 'User Menu' is pretty outdated after updates elsewhere in the app. Let's update it.

The streamlined version could look like this:
![Screenshot from 2024-04-29 17-56-29](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/438916b5-4a1e-485b-b323-3044854e0ac5)

With:

1. My Account - no change
2. My Maps - link to the same place as 'Open' in the map menu, that enables the user to open both own maps and maps shared with them.
3. Logout - same function but no need for the big green button
4. Donate - could this link be updated to direct to: https://opencollective.com/digitalcommonscoop

## Acceptance Criteria
1. Functionality as described above :)

**Comment by rogup** [comment]
How should we track this in Clockify? @lin-d-hop

**Comment by ms0ur1s** [comment]
@lin-d-hop, complete as per requirements, but was unsure whether there was any design update required.
