### ISSUE TITLE
Cannot save polygon to layer or map

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#326]
**Clockify to the F&G project**

**Describe the bug**
I cannot save a poly to a map or save polys to layers.

I have tried this from two accounts. 

**To Reproduce**
1. Create a poly
2. Edit the poly name
3. Try to save the map. See error
4. try to add to a layer. See error.

**Expected behaviour**
I should be able to save polys with names to maps and layers.

**Screenshots/GIFs**

![Screenshot from 2024-07-15 11-22-13](https://github.com/user-attachments/assets/d3b4d847-e8d4-4ca5-84e1-bc2de67967ec)
![Screenshot from 2024-07-15 11-22-31](https://github.com/user-attachments/assets/f8929052-b551-4cea-af3c-81d0b7aae833)

**Context (please complete the following information):**
 - Device: Desktop
 - OS: Ubuntu
 - Browser : Chrome and Brave

**Comment by rogup** [comment]
I'm not able to reproduce this. Is this on production?

Looking at the rubbish logs that we currently have, I can see there have been some jsonwebtoken errors recently (although not sure exactly when). Have you tried logging out / doing a hard refresh?

**Comment by lin-d-hop** [comment]
Yes I have tried those things.

Is there a max length to a poly name?
I shortened the length of the name from the required name and it saved ok. The error happened consistently on multiple accounts and browsers (as stated on the issue). But each time with a long name...

**Comment by rogup** [comment]
@lin-d-hop The max length is 45 characters (not really sure why it's that short)

**Comment by lin-d-hop** [comment]
Yeah we do need to have at least some kind of error. It's silly that I've made that mistake a few times now.
TODO for me to update the issue.
