### ISSUE TITLE
Pick up updates to Land Reg/INSPIRE dataset

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#47]
## Description

Land Reg INSPIRE data set is updated weekly, however we are not picking up those updates. We need a regular weekly job that updates our database. 

## Acceptance Criteria

- Weekly updates to Land Reg data are picked up
- Data job is done at a time that minimises potential disruption to usage
- Team is notified when the job is completed or if it fails. We should ensure these notifications are managed in alignment with other monitoring processes across DC. If we need to put some time into DC monitoring processes let's open that conversation :)

## Implementation Tasks

From a meeting with Tom and John 24/11. Notes [here](https://docs.google.com/document/d/1jfE0WlCRiZlsVEh_1WMkl-6_JKXixhO3BHynLLL7vGw/edit).

Update from meeting with Nick, John and Marcel 3/8/23
- [ ] Changing Deployment System. Addition to the existing playbook that provisions servers for digital commons, that installs necessary tools for a service running at boundaryservice.landexplorer.app. Est. 2 days

- [ ] Merging MykoMap and LX servers so that there’s a dev and a staging server for both, and they’re deployed in the same way. Requires itemisation, don’t know estimate.

- [ ] Migrating existing data (more than 20GB, less than 30GB). Est 2 days

- [ ] Job that triggers updates. est. 1 day

- [x] Fetch data from INSPIRE Est. 2 days - the data is broken up by council and not accessed in an easy to use api format

- [ ] Fetch company data ½ day

- [ ] Match up above 2 datasets Uncertain, 3 days maybe more

- [ ] Put in database 1 day

- [ ] Write route for querying database ½ day

- [ ] Write simple auth system for service 1 day

- [ ] LX back-end request ½ day

**Comment by King-Mob** [comment]
@ThomasDavisonsGit and I have had a discussion about whether he can start this work with support from me and @wu-lee . We had a call yesterday where I delivered a verbal specification and described the current state of affairs.

He's been actioned to create a document based on the call, so we have a written spec and to contact Hansen to understand how the first version of the boundary service (essentially a large database) was created.

We're going to have a conversation after the documentation is up and before initialising a codebase. The two fixed points for the codebase are that it will be in typescript and have unit tests.

Thomas will report in on element in the datafactory channel.

**Comment by lin-d-hop** [comment]
The goal is to get to a place when you are ready to pair with John on writing this in typescript.

- Message Hansen to arrange picking his brain and documenting the manual generation process
- Install Typescript dev env

**Comment by lin-d-hop** [comment]
Hi @ThomasDavisonsGit
Have you made any progress with this? Any updates?:)

**Comment by lin-d-hop** [comment]
Hi @ThomasDavisonsGit Thanks for the work documenting the steps you plan to take for this task.
How are you getting on with the steps?

**Comment by lin-d-hop** [comment]
Notes from meetings 26/01

- Typescript code takes data from zip from LR, opens, coverts from GML to GeoJson. Current task is translating Hansen's PHP code into typescript. Hansen used a framework that entered lots of irrelevant code. Tom talking to Hansen to try and unpack this curly mess.
- Tom going to hand over the part to download the zip. Needs issue.
- Time to create a repo for the data factory :tada:

**Comment by ThomasDavisonsGit** [comment]
Update on the 5 steps I am aiming to complete:

1. Download a zip file - getting ``TypeError: fetch failed``, an issue with the zip's URL, looking into it. Checking out URL headers and other info using Postman.
2. Unzip the zip file - done.
3. Convert gml to geojson - ogr2ogr command line tool (with some connection error...) works. The conversion seems to conserve all data, great.
(3.2. ogr2ogr also has an npm package to do this, at the moment this is printing unhelpfil "data" to terminal, but we need geojson "text" instead)
4. Reformat geojson data and insert into our mysql database - Hansen's php script does this, I am attempting to convert it all to TS, whilst figuring out how exactly it is manipulating the data. I am making progress with setting up and running the php script, this will help me see precisely what needs to be done with the data, I am in discussion with Hansen.
5. Do all this for batch of multiple zips - not yet looked at.

**Comment by lin-d-hop** [comment]
Repo with Tom's investigations: https://github.com/DigitalCommons/inspire_updater

**Comment by lin-d-hop** [comment]
@ThomasDavisonsGit Can we also share a link to Hansen's code too please?

**Comment by rogup** [comment]
@King-Mob Do you know where we were planning to run this app to fetch INSPIRE data?
I feel like it makes most sense to run it on the same server as the 'boundary service' which is currently just a MySql database, not really a service.

I've been talking to @wu-lee and if we do this, makes sense for us to use Ansible and/or Docker, so that this app can be redeployed and maintained more easily.

For https://github.com/DigitalCommons/land-explorer-front-end/issues/59 I'm going to just deploy the database on a Hetzner server on its own, like how it is currently on Cloudways, then the Ansible/Docker config can be set up later, once this app has been created.

**Comment by King-Mob** [comment]
@lin-d-hop regarding the matching task, it might be we need to do some geocoding from the address of the UK company land data back to the polygons. this has an associated cost to it.

I can't give you firm proportions of how many we might want to do this for, vs what we can get with the data we already have, but I should be able to in a couple of weeks (I'm not here next week)

**Comment by lin-d-hop** [comment]
Am I right that there is an option to just download the changes on the Land Reg ownership data? That will keep costs down for future updates and allow us to stay more up to date. I guess in this update we can also just do the geocoding for any polys with changed ownership compared to what we have in the DB.

**Comment by lin-d-hop** [comment]
John and I broke this into three phases:

- [ ] 1. Get the typescript roll out live (staging)

- [ ] 2. INSPIRE updates - We have some more thinking to do wrt patching the existing land reg data.

- [ ] 3. Companies house updates

**Comment by rogup** [comment]
Hi @King-Mob is the status of the tickboxes in this issue (in the description and latest comment) up to date? Would help to understand the codebase when I look through it

**Comment by King-Mob** [comment]
@rogup disregard check boxes, mostly done

**Comment by lin-d-hop** [comment]
Notes from Lynne and John last chat Nov 21st:
https://docs.google.com/document/d/1ZkmwqwodVZPo9RyzZy5HIhQf8KuPa5Z4W6Rv7kO1nl0/edit

**Comment by lin-d-hop** [comment]
Closing this issue to clear out the muddy terrain. Dredging if you will.
