### ISSUE TITLE
save -> save as new map, doesn't work

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#66]

**Comment by lin-d-hop** [comment]
Tested with a saved map loaded and one layer open.
Hit 'save as new map'. 
On saving the new map, it failed to save and I remained on the existing map.

https://user-images.githubusercontent.com/8669848/177520286-fc961a3c-961e-4961-b305-e47caecbd8e0.mp4

So this hasn't been fully fixed. Back to InDev
