### ISSUE TITLE
Support loading and display of sets of SEAInitiatives into Land Explorer 

### ISSUE THREAD

**Issue by ColmMassey** [DigitalCommons/land-explorer-front-end#8]
Start with a regional data set, like Mersey Green, say. Do minimum to get working as a simple layer.

**Comment by ColmMassey** [comment]
Cool. What data has this been tested on?

**Comment by lin-d-hop** [comment]
Closed as this is not a well described issue and as discussed in the meeting yesterday will be superseded by work on the Data Factory.
