### ISSUE TITLE
Add item_type relationship to data model

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#81]
## Description

We need to change the way that maps are saved. Currently when a map with markers is saved the map is saved as a json string. When there are too many markers this string overloads and the map cannot be saved. The solution to this is to create a map_memberships table in the DB that, for any saved map id (which we will start calling views) will contain the approriate references to data on this map.

## Acceptance Criteria

- Saved maps have an ID associated with them
- A new table in the DB - map_memberships
- A new table in the DB: item_types
- map_memberships will need the following cols: 
    id - self explanatory
    map_id - referring to the saved map
    item_type_id - referring to the item type table, which contains a list of possible item types (which may or may not be tables)
    item_id - referring to the id of the item, now we know where to look with item_type_id
- item_types will need the following cols:
    id - self explanatory
    name - aim to keep this machine readable eg table names
    description - help the humans understand
    source - static types for which we'll only have something for LX DB to start

**Comment by lin-d-hop** [comment]
The way I envisage the source table is a bunch of static types. In the mid term they might be:
- LX_DB
- PARTNER111_DB
- DATA_FACTORY
- PATNER112_API

This could then enable switch blocks in the code to fetch the data. 

For now we only have one source - LX_DB.

Hope that helps clarify.

**Comment by King-Mob** [comment]
Yep, make sense

**Comment by King-Mob** [comment]
this isn't up on staging yet, it'll probably be in the same PR as #90, and they're both on the back-end

**Comment by lin-d-hop** [comment]
Is this in Review for a reason if I can't test it yet? @King-Mob
