### ISSUE TITLE
Drawn markers use the new marker data model

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#90]
## Description
When markers are drawn in LX they are saved only in the map json for the specific map you are in. 
We would like to instead persist these markers in the 'markers' DB such that the features and sharing options are consistent across both marker types.

## Acceptance Criteria
- Drawn markers have the ability to save descriptions alongside names and locations
- Drawn markers can be added to data_groups
- Drawn markers can still be saved to specific maps and exported as they currently can

**Comment by King-Mob** [comment]
@rogup do you have a PR for this?
